### PR TITLE
chore: Dart 3 maintenance

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

- Updated various dependencies
- Added a root repo pubspec (required by melos 3.x)
- Prevented the execution of the /tools scripts in GH actions
  - Copied and simplified the scripts to work inline

Note: the scripts are now in two places (composite actions + tools/ dir)
Reason for this being that I'm aware of potential actions leakage by calling scripts from the tools/ directory, however someone else may not be aware. This protects against that issue if someone else contributes to at_app and I'm not the reviewer.

**- How I did it**

**- How to verify it**

**- Description for the changelog**
chore: Dart 3 maintenance

### CODE REVIEW

**Comment by xavierchanth** [comment]
Cleaning up the CI a bit before I upgrade all of the templates.
(Which will be done in a new PR)

**Comment by xavierchanth** [comment]
`dart-3-templates` branch will contain the changes which fix the CI here, what's happening is that there are some much needed code changes due to the breaking changes in mason's dev channel... (hence why it has been pinned for the past 30+ versions of mason)

**Comment by cpswan** [comment]
@XavierChanth lots going on here, so let's use our 1-2-1 to walk through it.

**Comment by xavierchanth** [comment]
Superceded by #281

**Pull request closed without merging**
