### PR TITLE
feat: at_follows_flutter sample

### PR DESCRIPTION
**Pull request by CemTitor**
**- What I did**

- Added sample from at_widgets repository
  - Added at_follows_flutter
- Added json-schemas for brick.yaml and pubspec.yaml to make template maintenance easier

**- How I did it**

- Copied the lib folder from at_widgets repository, wrote the necessary config files
- Built and bundled at_app
 
**- How to verify it**
1. Pull this branch
2. List the samples with `dart run at_app/bin/at_app.dart create --list-samples`
3. Run `dart run at_app/bin/at_app.dart create -s at_follows_flutter <path/to/output>` 
4. Run generated sample app and verify that it work

**- Description for the changelog**
Added at_follows_flutter sample to trunk

### CODE REVIEW

**Comment by CemTitor** [comment]
For now after app build with
$ dart pub global run melos run build:generated -- sample at_follows_flutter

Like a "file_saver" package,
"share_plus" package must be added as a dependency overrides into pubpsec.yaml of builded app like this:


```
dependency_overrides:
  at_app_flutter:
    path: ../../../packages/at_app_flutter
  file_saver:
    git:
      url: https://github.com/incrediblezayed/file_saver.git
      ref: main
  share_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/share_plus/share_plus/
      ref: main
```

**Comment by xavierchanth** [comment]
> For now after app build with $ dart pub global run melos run build:generated -- sample at_follows_flutter
> 
> Like a "file_saver" package, "share_plus" package must be added as a dependency overrides into pubpsec.yaml of builded app like this:
> 
> ```
> dependency_overrides:
>   at_app_flutter:
>     path: ../../../packages/at_app_flutter
>   file_saver:
>     git:
>       url: https://github.com/incrediblezayed/file_saver.git
>       ref: main
>   share_plus:
>     git:
>       url: https://github.com/fluttercommunity/plus_plugins.git
>       path: packages/share_plus/share_plus/
>       ref: main
> ```

@CemTitor please explain further why this dependency override is required.

**Comment by CemTitor** [comment]
I was getting this error without share_plus package


```
e: C:\src\flutter\flutter\.pub-cache\git\plus_plugins-ca6f0d95cff4435608679f66da374a126979a600\packages\share_plus\share_plus\android\src\main\kotl
in\dev\fluttercommunity\plus\share\MethodCallHandler.kt: (9, 16): Redeclaration: MethodCallHandler
e: C:\src\flutter\flutter\.pub-cache\git\plus_plugins-ca6f0d95cff4435608679f66da374a126979a600\packages\share_plus\share_plus\android\src\main\kotl
in\dev\fluttercommunity\plus\share\Share.kt: (19, 16): Redeclaration: Share
e: C:\src\flutter\flutter\.pub-cache\git\plus_plugins-ca6f0d95cff4435608679f66da374a126979a600\packages\share_plus\share_plus\android\src\main\kotl
in\dev\fluttercommunity\plus\share\ShareFileProvider.kt: (10, 7): Redeclaration: ShareFileProvider
e: C:\src\flutter\flutter\.pub-cache\git\plus_plugins-ca6f0d95cff4435608679f66da374a126979a600\packages\share_plus\share_plus\android\src\main\kotl
in\dev\fluttercommunity\plus\share\SharePlusPlugin.kt: (10, 7): Redeclaration: SharePlusPlugin
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-3.1.0\android\src\main\kotlin\dev\fluttercommunity\plus\share\MethodCallHan
dler.kt: (8, 16): Redeclaration: MethodCallHandler
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-3.1.0\android\src\main\kotlin\dev\fluttercommunity\plus\share\MethodCallHan
dler.kt: (18, 9): No value passed for parameter 'withResult'
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-3.1.0\android\src\main\kotlin\dev\fluttercommunity\plus\share\MethodCallHan
dler.kt: (31, 11): No value passed for parameter 'withResult'
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-3.1.0\android\src\main\kotlin\dev\fluttercommunity\plus\share\MethodCallHan
dler.kt: (34, 24): Type mismatch: inferred type is String? but String was expected
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-3.1.0\android\src\main\kotlin\dev\fluttercommunity\plus\share\Share.kt: (17
, 16): Redeclaration: Share
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-3.1.0\android\src\main\kotlin\dev\fluttercommunity\plus\share\ShareFileProv
ider.kt: (10, 7): Redeclaration: ShareFileProvider
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-3.1.0\android\src\main\kotlin\dev\fluttercommunity\plus\share\SharePlusPlug
in.kt: (10, 7): Redeclaration: SharePlusPlugin
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-3.1.0\android\src\main\kotlin\dev\fluttercommunity\plus\share\SharePlusPlug
in.kt: (16, 72): No value passed for parameter 'manager'
e: C:\src\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\share_plus-3.1.0\android\src\main\kotlin\dev\fluttercommunity\plus\share\SharePlusPlug
in.kt: (17, 42): No value passed for parameter 'manager'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':share_plus:compileDebugKotlin'.
> Compilation error. See log for more details
```


And when i added this package as a normal dependency, there is a dependency conflict between share_plus and at_follows_flutter

**Comment by xavierchanth** [comment]
@CemTitor this is share_plus version 3, latest is version 4. Have you tried using latest available on pub before using git dependencies?

**Comment by CemTitor** [comment]
@XavierChanth  Yes, I tried the latest version. When I pub get with latest version, here is my error:

```
Running "flutter pub get" in at_follows_flutter...              
    Because at_onboarding_flutter >=4.0.1 depends on permission_handler ^9.2.0 and no versions of at_onboarding_flutter match >4.0.0 <4.0.1, at_onboarding_flutter >4.0.0 requires permission_handler ^9.2.0.
(1) So, because at_onboarding_flutter 4.0.0 depends on at_backupkey_flutter ^4.0.0, at_onboarding_flutter >=4.0.0 requires permission_handler ^9.2.0 or at_backupkey_flutter ^4.0.0.

    Because at_backupkey_flutter >=4.0.1 depends on permission_handler ^9.2.0 and no versions of at_backupkey_flutter match >4.0.0 <4.0.1, at_backupkey_flutter >4.0.0 requires permission_handler ^9.2.0.
    And because at_backupkey_flutter 4.0.0 depends on share_plus ^3.0.4, at_backupkey_flutter >=4.0.0 requires share_plus ^3.0.4 or permission_handler ^9.2.0.
    And because at_onboarding_flutter >=4.0.0 requires permission_handler ^9.2.0 or at_backupkey_flutter ^4.0.0 (1), at_onboarding_flutter >=4.0.0 requires permission_handler ^9.2.0 or share_plus ^3.0.4.
    Because no versions of at_follows_flutter match >3.0.7 <4.0.0 and at_follows_flutter 3.0.7 depends on permission_handler ^8.3.0, at_follows_flutter ^3.0.7 requires permission_handler ^8.3.0.
    Thus, if at_follows_flutter ^3.0.7 and at_onboarding_flutter >=4.0.0 then share_plus ^3.0.4.
    And because at_follows_flutter_test_app depends on at_onboarding_flutter ^4.0.0, at_follows_flutter ^3.0.7 requires share_plus ^3.0.4.
    So, because at_follows_flutter_test_app depends on both at_follows_flutter ^3.0.7 and share_plus ^4.0.10, version solving failed.
pub get failed (1;     So, because at_follows_flutter_test_app depends on both at_follows_flutter ^3.0.7 and share_plus ^4.0.10, version solving failed.)
Process finished with exit code 1
```

**Review by xavierchanth — APPROVED** [review]

**Pull request merged**
