### PR TITLE
chore: test & release of 5.0.0

### PR DESCRIPTION
**Pull request by Xlin123**
**- What I did**
Tested and fixed templates/<template>/pubspecs.
[#293](https://github.com/atsign-foundation/at_app/issues/293) 
**- How I did it**

**- How to verify it**

**- Description for the changelog**
Test & release of 5.0.0

### CODE REVIEW

**Comment by xavierchanth** [comment]
We should update at_chat_flutter to support onboarding 6, rather than downgrade onboarding to 5. But that means we need to publish a new version of at_chat_flutter first...

**Comment by Xlin123** [comment]
Should be good, all templates running well. Didn't take too long once I understood everything and had the time to work on it.

**Review by xavierchanth — APPROVED** [review]
Thanks so much!

**Comment by xavierchanth** [comment]
@Xlin123 would you like to do the honours of publishing to pub.dev?

**Comment by Xlin123** [comment]
Can you merge it before I publish :)

**Pull request merged**
