### PR TITLE
chore: Update android config

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

Build tools (`tools/*`): 
- Updated permissions of the build scripts
- Shellcheck fixes

Android build config base template (`at_app_create/**`):
- Updated `gradle` version, `kotlin` version, default values for `compileSdkVersion`, `minSdkVersion`, and `targetSdkVersion`.

Template config (`templates/*/*/pubspec.yaml`):
- Removed android build configuration overrides
- Added dependency overrides for `biometric_storage: ^4.1.3`

**- How I did it**

Local changes.

**- How to verify it**

Pull and run the build pipeline, test locally.

**- Description for the changelog**
chore: Update android config

### CODE REVIEW

**Comment by sachins-geekyants** [comment]
@XavierChanth this PR(https://github.com/atsign-foundation/at_client_sdk/pull/717) upgrades `biometric_storage` version in at_client_mobile, which fixes one of android build issue.

Can we wait till new `at_client_mobile` and `at_onboarding_flutter` version is released with `biometric_storage: 4.1.3` ?

**Comment by xavierchanth** [comment]
Pending: https://github.com/atsign-foundation/at_client_sdk/pull/717

**Comment by xavierchanth** [comment]
Linking to main issue card: https://github.com/atsign-foundation/apps/issues/720

**Comment by xavierchanth** [comment]
@sachins-geekyants build is failing due to the biometric_storage version, once at_client_mobile is released supporting biometric_storage 4.1.3 we can rerun tests.

**Pull request merged**
