### PR TITLE
chore: Prepare at_app, at_app_create, at_app_bundler for release

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

Updated version number and changelog for at_app, at_app_create, and at_app_bundler.

**- How I did it**

Local changes.

**- How to verify it**

**- Description for the changelog**
chore: Prepare at_app, at_app_create, at_app_bundler for release

### CODE REVIEW

**Comment by xavierchanth** [comment]
The test failed since it is trying to resolve a dependency which hasn't been published yet... melos has been misbehaving recently, it hasn't been consistent in doing its job of locally linking dependencies.

**Comment by xavierchanth** [comment]
Why the build failed:

Running build_runner as a dev_dependency (`dart run build_runner build`) causes pub get to be called first (which subsequently attempts to unlink the local packages)... I don't believe this to be the behaviour before. However, running build_runner as a global dependency does not cause pub get to be called first so that is what I've opted to do.

All in all, a very niche behavioural interaction that is at least worth documenting here.

**Comment by xavierchanth** [comment]
The same issue is occurring with `dart test` :)

**Comment by xavierchanth** [comment]
Rabbit hole: https://github.com/dart-lang/sdk/issues/45307

`flutter test` has a `--no-pub` flag, so will be using that instead.

**Review by cpswan — APPROVED** [review]

**Pull request merged**
